### PR TITLE
update bettercap to 2.32.0

### PR DESCRIPTION
**Pull request by OldiLo**

### CODE REVIEW

**Comment by etmatrix** [comment]
Have you tried it?
From bettercap 2.30.1 there is a new module used in modules/packet_proxy/packet_proxy_linux.go github.com/chifflier/nfqueue-go/nfqueue which require libnetfilter-queue, termux has not this library.

**Comment by OldiLo** [comment]
I deleted fix-home-path.patch because ~ symbol is $HOME directory

**Comment by etmatrix** [comment]
>  ~ symbol is $HOME directory

sure but maybe it's not working, I think if someone replace it with @TERMUX_HOME@ there must be a reason
Anyway libnetfilter-queue is missing and I can't find a way for build with clang too many errors.

**Comment by Grimler91** [comment]
Patches look good, not sure why I decided to patch "~" to hardcode the home dir path instead. 

We will need to add a libnetqueue_filter package to make it build. x86_64 hasn't build in quite a while for the same reason: https://github.com/termux/termux-root-packages/blob/master/packages/bettercap/build.sh#L10

**Comment by etmatrix** [comment]
[https://github.com/bettercap/bettercap/commit/e0ff16f9f1ded93c8cd54976449c58b5d2c9f317#diff-8b9cc9c12e97d21aee7e01be7737719d56b69f784a4f622c67f731e4b42ccc95](This) commit add the dependency to package "github.com/chifflier/nfqueue-go/nfqueue" (nfqueue-go is a wrapper library for libnetfilter-queue. )

I'm to fix the compilation errors but I got everyone a new one. I'm testing on arm64

**Comment by etmatrix** [comment]
I successfully build libnetfilter_queue but I have replaced 2 file on ndk_sysroot

/data/data/com.termux/files/usr/include/netinet/if_ether.h
/data/data/com.termux/files/usr/include/linux/netfilter/nfnetlink.h

taken from debian system
I applied a simple patch to src/extra/tcp.c

I'm search a way for build without replace that 2 files

**Comment by etmatrix** [comment]
> Patches look good

the submited patch is wrong. 
Code in modules/ui/ui.go is changed, the pull request is submited without test.

this is the correct patch

```
diff --git a/caplets/env.go b/caplets/env.go
index 9ba8706..fd12078 100644
--- a/caplets/env.go
+++ b/caplets/env.go
@@ -19,7 +19,7 @@ func getDefaultInstallBase() string {
        if runtime.GOOS == "windows" {
                return filepath.Join(os.Getenv("ALLUSERSPROFILE"), "bettercap")
        }
-       return "/usr/local/share/bettercap/"
+       return "@TERMUX_PREFIX@/share/bettercap/"
 }
 
 func getUserHomeDir() string {
diff --git a/modules/ui/ui.go b/modules/ui/ui.go
index 7bc5270..9a5476a 100644
--- a/modules/ui/ui.go
+++ b/modules/ui/ui.go
@@ -34,7 +34,7 @@ func getDefaultInstallBase() string {
        if runtime.GOOS == "windows" {
                return filepath.Join(os.Getenv("ALLUSERSPROFILE"), "bettercap")
        }
-       return "/usr/local/share/bettercap/"
+       return "@TERMUX_PREFIX@/share/bettercap/"
 }
 
 func NewUIModule(s *session.Session) *UIModule {
```
bettercap 2.32.0 now compile but there is an issue when I run

```
~ # bettercap -iface mon0
CANNOT LINK EXECUTABLE "bettercap": cannot locate symbol "IPTOS_TOS" referenced by "/data/data/com.termux/files/usr/lib/libnetfilter_queue.so"...
```

**Comment by etmatrix** [comment]
I replaced also `/data/data/com.termux/files/usr/include/netinet/ip.h` in ndk_systoor IPTOS_TOS was a define
Now bettercap compile, run and I can test wifi successfully

**Comment by Grimler91** [comment]
@etmatrix thanks for looking at it! Do you want to open a new PR to add libnetfilter_queue and to update bettercap? 
Rather than patching the ndk headers we probably want to patch bettercap. 
A PR that the CI can test would visualise what happens, and what needs to be changed

**Comment by etmatrix** [comment]
> Do you want to open a new PR to add libnetfilter_queue and to update bettercap? 

sure but I must solve how to compile libnetfilter_queue without replace include file or do you think I can replace with a command in pre_configure?
The build environment everytime is cleaned or am I wrong?

**Comment by Grimler91** [comment]
> sure but I must solve how to compile libnetfilter_queue without replace include file or do you think I can replace them with a command in pre_configure? 

I think the issues can be solved with a patch to the libnetfilter_queue package, either by adding some definitions, or by modifying some `if defined(...)` line (haven't seen the actual error yet though)

> The build environment everytime is cleaned or am I wrong?

In the CI builds everything is cleaned, so we should strive after having a successful build in a clean environment

**Comment by OldiLo** [comment]
ibnetfilter_queue is not require to bettercap

**Comment by OldiLo** [comment]
i create patch for packet proxy module, should help

**Comment by etmatrix** [comment]
I submitted package libnfnetlink and libnetfilter-queue and bettercap should compile without changes

**Pull request closed without merging**
