### PR TITLE
Enable squashfs package after some successful tests

### PR DESCRIPTION
**Pull request by FreddieOliveira**
@Grimler91 I don't really understand how this build.sh script works, and to be honest I didn't test it. Verify closely if things are correct.

Here are some questions I have:

1. Do I need to specify `--prefix` flag for configure args? From what I checked no other package uses it.
2. Do I need the `TERMUX_PKG_REVISION`? Only a few packages use it.
3. Do I need to use a release tarball or can I compile a package directly from the last commit of its github page?
4. Does the build script runs `make install` automatically?

### CODE REVIEW

**Comment by Grimler91** [comment]
Hey, 

1. No, it should be [added automatically](https://github.com/termux/termux-packages/blob/ebb026d03bc452701bdd59e6f216a7ee57425b9e/scripts/build/configure/termux_step_configure_autotools.sh#L103)
2. It is only needed when a packaged is changed (not for new packages as in this case), it defaults to 0
3. Using latest commit is okay but it should use a commit and not just master.tar.gz, and it should be noted in the package version (so `0.1.103-git` or similar)
4. [It is run automatically](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_make_install.sh)

**Comment by Grimler91** [comment]
I don't have permission to edit your branch, so could you delete the TERMUX_PKG_REVISION line and not set TERMUX_EXTRA_CONFIGURE_ARGS so that we can see if the CI finishes successfully in that case?

**Comment by FreddieOliveira** [comment]
Thanks for the explanation, I didn't know about those build scripts. I'll read them later so I can start openning PR instead of issues for package request.

I happened to see EncFS is also in the disabled limbo. I was already able to run it [8 months ago](https://github.com/termux/termux-packages/issues/286#issuecomment-632349287). Is there any specific reason for it being disabled or a PR would be accepted? I can work on this if desired.

**Comment by FreddieOliveira** [comment]
> I don't have permission to edit your branch

I've just enabled edits. If there's anything missing I guess you can now edit.

**Comment by Grimler91** [comment]
> Thanks for the explanation, I didn't know about those build scripts. I'll read them later so I can start openning PR instead of issues for package request.

Sounds great :) you have some more docs/info about the build process here: https://github.com/termux/termux-packages/wiki/Building-packages, https://github.com/termux/termux-packages/wiki/Build-environment

> I happened to see EncFS is also in the disabled limbo. I was already able to run it 8 months ago. Is there any specific reason for it being disabled or a PR would be accepted? I can work on this if desired.

No particular reason, I have just not tested and packaged it. If you open a PR I can help solve potential packaging issues, and merge it into the repo.

**Review by johndoeuser21 — APPROVED** [review]

**Comment by johndoeuser21** [comment]
Ehcj

**Pull request merged**
