### PR TITLE
wpa-supplicant: add package

### PR DESCRIPTION
**Pull request by Grimler91**
Should test it before merging

### CODE REVIEW

**Comment by drygdryg** [comment]
How can I help with testing?

**Comment by Grimler91** [comment]
@drygdryg please install this deb: https://grimler.se/dists/testing/misc/binary-aarch64/wpa-supplicant_2.9_aarch64.deb (replace aarch64 with your arch if you are on another one), and give it a try (with a usb wifi stick I suppose), thanks!

**Comment by drygdryg** [comment]
@Grimler91 tried on my 2 devices (arm and aarch64) with internal Wi-Fi — it works fine.

**Comment by Grimler91** [comment]
Alright, thanks, let's add it then!

**Comment by drygdryg** [comment]
Thanks so much!

**Pull request merged**
