### PR TITLE
[libnetfilter_queue] this library is required for build bettercap 2.32.0

### PR DESCRIPTION
**Pull request by etmatrix**
require changes of these include files in ndk_sysrooty:
/data/data/com.termux/files/usr/include/netinet/if_ether.h
/data/data/com.termux/files/usr/include/netinet/ip.h
/data/data/com.termux/files/usr/include/linux/netfilter/nfnetlink.h

### CODE REVIEW

**Comment by Grimler91** [comment]
This is weird, CI is not picking up the commit even after rebasing

**Comment by etmatrix** [comment]
too many PR?

**Comment by etmatrix** [comment]
On my environment if TERMUX_PKG_LICENSE_FILE is not present give me error

**Comment by Grimler91** [comment]
I don't know why it does not want to test build this PR, it worked for the [bettercap PR](https://github.com/termux/termux-root-packages/pull/269) so seems to be some issue with just the libnetfilter_queue commit, for some reason.

Building locally works fine anyways, I see the errors about redefinition of a bunch of symbols like `error: redefinition of 'nfnetlink_groups'`. 

> On my environment if TERMUX_PKG_LICENSE_FILE is not present give me error

It should work after changing to GPL-2.0, it then uses a shared GPL-2.0 license instead of looking for one in the source directory

**Comment by thunder-coding** [comment]
The CI isn't picking this up because of `_` in package name

**Comment by etmatrix** [comment]
> The CI isn't picking this up because of `_` in package name

ok thank you a rename with -

**Comment by etmatrix** [comment]
after git mv push doesn't work, I rename the branch and maked a new PR. Sorry!

**Pull request closed without merging**
