### PR TITLE
Add containerd package

### PR DESCRIPTION
**Pull request by FreddieOliveira**
Containerd is actually a docker dependency. Pls, check if the build script is correct since the other packages (dockerd and dockercli) will have the same structure.

### CODE REVIEW

**Comment by FreddieOliveira** [comment]
i686 test failed with: `/tmp/go-link-949764692/go.o:go.go:_cgo_init: error: undefined reference to 'x_cgo_init'` I'm not sure why. I didn't have this issue here compiling for aarch64.

**Comment by FreddieOliveira** [comment]
It seems it has to do with `CGO_ENABLED` var being 0. Setting it to 1 may fix the problem. I didn't try though. I compiled the package on my device inside Termux. Maybe this is the case to mark this package as TERMUX_ON_DEVICE_BUILD or setting CGO_ENABLED for cross compilation.

**Comment by xeffyr** [comment]
> It seems it has to do with CGO_ENABLED var being 0.

CGO must be always on for Android.

**Comment by xeffyr** [comment]
Your build.sh won't work here due to attempt to run cross-compiled executable:
```
go run cmd/gen-manpages/main.go containerd.8 man
fork/exec /tmp/go-build640298035/b001/exe/main: exec format error
make: *** [Makefile:225: man/ctr.8] Error 1
make: *** Waiting for unfinished jobs....
fork/exec /tmp/go-build266114902/b001/exe/main: exec format error
```

You need to reset variables `GOARCH`, `GOOS` and others set by build-package.sh when compiling program which should run on host environment.

**Comment by FreddieOliveira** [comment]
I've checked the test logs and it built the binaries successfully, but failed when generating the man pages. I'll try to figure out why exactly.

**Comment by FreddieOliveira** [comment]
When running make man, it complies an auxiliary executable called md2man. Then, it uses this executable to generate the manuals. Probably that's when the error arises, because this binary shouldn't be cross compiled. I'll try to unset the env vars before executing make man

**Comment by FreddieOliveira** [comment]
```
gcc_amd64.S:25:8: error: unknown token in expression
 pushq %rbx
       ^
gcc_amd64.S:25:8: error: invalid operand
 pushq %rbx
       ^
```
Generating a man page turned out to be more hassle than generating the binary itself.

**Comment by xeffyr** [comment]
@FreddieOliveira `unset GOOS GOARCH CGO_LDFLAGS CC CXX CFLAGS CXXFLAGS LDFLAGS`. Look build.sh of `hugo` from termux-packages, it does similar steps to generate manpages.

**Comment by FreddieOliveira** [comment]
> Look build.sh of hugo from termux-packages, it does similar steps to generate manpages.

Cool, fixing the unsets solved the issue. But unfortunately it was able to compile only for aarch6.

**Comment by FreddieOliveira** [comment]
> Maybe that's fixable. I'll try to compile on device (inside Termux) in another phone I have arm32.

Indeed, it was fixable. When compiling in my other phone I was getting the very same undefined reference error, till I realize cgo needs to be enabled for other architectures other than aarch64, for whatever reason. I've unblacklisted the others archs and now it sucessfully builds for all of them.

@xeffyr I believe now we're good to go.

**Pull request merged**
