### PR TITLE
add package wireless-tools

### PR DESCRIPTION
**Pull request by xeffyr**
Dependency for #3

### CODE REVIEW

**Comment by xeffyr** [comment]
Some programs from aircrack-ng package have hardcoded calls to programs from wireless-tools (iwconfig & iwpriv).

Package iw should be moved to termux-root-packages because it requires root.

**Comment by Auxilus** [comment]
I'm on it..

**Comment by Auxilus** [comment]
@xeffyr I've also opened pr for tcpdump  https://github.com/termux/termux-root-packages/pull/6

**Comment by fornwall** [comment]
Do we really need to override `termux_step_make` and `termux_step_make_install`?

**Comment by xeffyr** [comment]
This step overrides are not needed due to patch so I will remove them.

**Comment by Deathlive** [comment]
@xeffyr Can you create a `.deb` iw package for installation ?

**Comment by xeffyr** [comment]
@Deathlive [wireless-tools_arm_aarm64.zip](https://github.com/termux/termux-root-packages/files/1478831/wireless-tools_arm_aarm64.zip) - for architectures ARM and AARCH64.

**Comment by Auxilus** [comment]
@xeffyr Im getting
```
[19:53]~/wireless-tools > iwconfig
error: only position independent executables (PIE) are supported.
```

**Comment by Auxilus** [comment]
with the deb file you provided

**Comment by xeffyr** [comment]
@Auxilus ok, I will check.

**Comment by xeffyr** [comment]
Possible that this is due to commit 1e336ea0c0d35834a67d6d0daf09c6bbcb3da835.

**Comment by xeffyr** [comment]
Archive with fixed debs: [wireless-tools_arm_aarch64.zip](https://github.com/termux/termux-root-packages/files/1478998/wireless-tools_arm_aarch64.zip)

**Comment by Deathlive** [comment]
`Warning: Driver for device ccmi0 has been compiled with an ancient version of Wireless Extension, while this program support vversion 11 and later.`
Can you give instructions how to compile your package yourself?

**Comment by xeffyr** [comment]
@Deathlive even if you compile it yourself, you will have an error:
```Driver for device ccmni0 has been compiled with an ancient version of Wireless Extension```.

Can you give output of command ```uname -a``` ? Possible that your kernel too old.

**Comment by Deathlive** [comment]
@xeffyr 
default

**Comment by xeffyr** [comment]
@Deathlive your kernel seems to be ok, but driver for **ccmni0** requires too old version of kernel wireless extensions so possible that you need a very old version of wireless-tools (v10 maybe?).

**Comment by Deathlive** [comment]
@xeffyr Can you test, does bettercap works ?
`gem install bettercap`
After launching `sudo bettercap -X` the program opens, but if the attacking browser goes to any site, then the sites do not load.
I just want to know the problem in `Warning: Driver for device ccmni0 has been...` or in something else.

**Comment by xeffyr** [comment]
Bettercap works really bad (and other sniffers that use ARP attack), ARP attack breaks network connections (ARP cache is empty on target device), ICMP redirect not working.

**Comment by xeffyr** [comment]
Just checked, all ARP attack tools including bettercap are working incorrectly on my PC (ArchLinux, no iptables rules, and ip forwarding enabled), but on my old device (running Android 2.3, kernel 2.6.37 + debian oldstable) all sniffer tools working very good.

So problem is on attacker's side, and possible that setting sysctl net.ipv4.ip_forward=1 is not enough on new kernels.

**Comment by Grimler91** [comment]
Thanks, this has been merged in dac4c40!

**Comment by Einsamerwolf2** [comment]
So how does work??

**Pull request closed without merging**
