### PR TITLE
add package aircrack-ng 

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by Auxilus** [comment]
I am hosting the patched tarball at Auxilus.github.io, so in the namefile I dont have mentioned the version

**Comment by xeffyr** [comment]
Ok, how it will be updated ? Version is needed for apt.

**Comment by Auxilus** [comment]
fixing it right now..

**Comment by Auxilus** [comment]
@xeffyr should be okay now..

**Comment by Auxilus** [comment]
@xeffyr is libmnl also gonna be in termux-root-packages?

**Comment by xeffyr** [comment]
It is not needed, I have just compiled aircrack without it.

**Comment by Auxilus** [comment]
👍

**Comment by Grimler91** [comment]
I had a look at this, after adding two patches it builds on all arches except aarch64. There it fails with:
```
aarch64-linux-android-clang  -Oz -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/data/data/com.termux/files/usr/include/libnl3 -fstack-protector -D_FILE_OFFS
ET_BITS=64 -D_REVISION=0  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/data/data/com.termux/files/usr/include/libnl3 -fstack-protector -Iinclude -I/data/data/com.termux/files/usr/include  -c -
o uniqueiv.o uniqueiv.c
In file included from sse-intrinsics.c:85:
In file included from /home/builder/.termux-build/_lib/16-aarch64-21-v3/lib64/clang/5.0.300080/include/emmintrin.h:27:
In file included from /home/builder/.termux-build/_lib/16-aarch64-21-v3/lib64/clang/5.0.300080/include/xmmintrin.h:27:
/home/builder/.termux-build/_lib/16-aarch64-21-v3/lib64/clang/5.0.300080/include/mmintrin.h:64:12: error:
      invalid conversion between vector type '__m64' (vector of 1 'long long' value) and
      integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
```
(and lots and lots of more output)

See branch at https://github.com/Grimler91/termux-root-packages/tree/aircrack-ng

**Pull request merged**
